# This pre-commit-config will set up pre-commit hooks.
# Setup:
## 1) Install Homebrew
## 2) Run 'brew install pre-commit'
## 3) Run 'pre-commit install --hook-type commit-msg --hook-type pre-commit --hook-type pre-push'

repos:
  - repo: local
    hooks:
    - id: swiftformat
      name: SwiftFormat
      entry: swiftformat
      language: system
      types: [swift]
      stages:
      - pre-commit
