# This pre-commit-config will set up pre-commit hooks.
# Install Homebrew
# Run 'brew install pre-commit'
# Run 'pre-commit install --hook-type commit-msg --hook-type pre-commit --hook-type pre-push'

repos:
  - repo: local
    hooks:
    - id: lockwood-swiftformat
      name: SwiftFormat
      entry: swiftformatt
      language: system
      types: [swift]
