# This workflow will build and test the BobbysCounter app.

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode 15.0.1
      run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app
    - name: Build setup
      run: >-
        xcodebuild test -workspace BobbysCounter.xcodeproj/project.xcworkspace
        -scheme BobbysCounter -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0'
    - name: Test iPhone 15 Pro
      run: >-
        xcodebuild test -workspace BobbysCounter.xcodeproj/project.xcworkspace
        -scheme BobbysCounter -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0'
    - name: Test iPad Pro (12.9-inch) (6th generation)
      run: >-
        xcodebuild test -workspace BobbysCounter.xcodeproj/project.xcworkspace
        -scheme BobbysCounter -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (6th generation),OS=17.0'
