# This workflow will test the BobbysCounter app.

name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        name: ['iPhone 16 Pro', 'iPad Pro 13-inch (M4)']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Run SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log --swiftversion 6.2
      - name: Run tests
        run: set -o pipefail && xcodebuild clean test -project BobbysCounter.xcodeproj -scheme BobbysCounter -destination 'platform=iOS Simulator,name=${{ matrix.name }},OS=latest' | xcbeautify --renderer github-actions
