# This workflow will test the BobbysCounter app.

name: Swift

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tests:
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
    - name: Test iPhone 15 Pro
      run: xcodebuild test -scheme BobbysCounter -project BobbysCounter.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15 Pro' | xcbeautify && exit ${PIPESTATUS[0]}
    - name: Test iPad Pro (12.9-inch) (6th generation)
      run: xcodebuild test -scheme BobbysCounter -project BobbysCounter.xcodeproj -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (6th generation)' | xcbeautify && exit ${PIPESTATUS[0]}
