# This workflow will test the BobbysCounter app.

name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  SwiftFormat:
    name: Run SwiftFormat
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Run SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log --swiftversion 6.0

  iPhone:
    name: Run tests (iPhone 16 Pro)
    needs: SwiftFormat
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Run tests
        run: set -o pipefail && xcodebuild test -project BobbysCounter.xcodeproj -scheme BobbysCounter -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' | xcbeautify --renderer github-actions
  iPad:
    name: Run tests (iPad Pro 13-inch (M4))
    needs: SwiftFormat
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Run tests
        run: set -o pipefail && xcodebuild test -project BobbysCounter.xcodeproj -scheme BobbysCounter -destination 'platform=iOS Simulator,name=iPad Pro 13-inch (M4),OS=latest' | xcbeautify --renderer github-actions
