# This workflow will test the BobbysCounter app.

name: Swift

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tests:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
    - name: SwiftFormat
      run: swiftformat --lint . --reporter github-actions-log --swiftversion 6.0
    - name: Build & Test iPhone 15 Pro
      run: xcodebuild test -scheme BobbysCounter -project BobbysCounter.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15 Pro' | xcbeautify && exit ${PIPESTATUS[0]}
    - name: Build & Test iPad Pro 13-inch (M4)
      run: xcodebuild test -scheme BobbysCounter clean build -project BobbysCounter.xcodeproj -destination 'platform=iOS Simulator,name=iPad Pro 13-inch (M4)' | xcbeautify && exit ${PIPESTATUS[0]}
