# This workflow will build and test the BobbysCounter app.

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-13

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
    - name: Test iPhone 15 Pro
      run: >-
        xcodebuild test -project BobbysCounter.xcodeproj
        -scheme BobbysCounter -destination 'platform=iOS Simulator,name=iPhone 15 Pro' | xcpretty -s
    - name: Test iPad Pro (12.9-inch) (6th generation)
      run: >-
        xcodebuild test -project BobbysCounter.xcodeproj
        -scheme BobbysCounter -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (6th generation)'| xcbeautify
